events {}

http {
    upstream backend_pool {
        server app1:5000 max_fails=2 fail_timeout=15s;
        server app2:5000 max_fails=2 fail_timeout=15s;
        server app3:5000 max_fails=2 fail_timeout=15s;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend_pool;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}